### ISSUE TITLE
对低分屏显示支持不友好

### ISSUE THREAD

**Issue by Er1cMa** [zqhong/RyzenTuner#1]
上图：
![image](https://user-images.githubusercontent.com/102273670/184106777-71bf1d80-e90d-4535-a329-6d0817cbdff1.png)
这是我1080p屏幕上的观感（宋体在缩小的时候的老毛病了）
建议找找别的字体（各种黑体会舒服一点）……或者调大字号

**Comment by zqhong** [comment]
好的，后续我注意下这个问题

**Comment by zqhong** [comment]
目前会尝试依次使用微软雅黑、思源黑体、Arial这三种字体。
如果系统没有这些字体，则使用默认值。

效果图：
![image](https://user-images.githubusercontent.com/8402647/184374985-942ee666-fce2-4cec-a5db-3e20a56b3573.png)

相关提交：
https://github.com/zqhong/RyzenTuner/commit/3feb95de2dd0f37fd0d901850b2fd11687fefebf
