### ISSUE TITLE
修改内置模式功率不生效

### ISSUE THREAD

**Issue by SimonWe1** [zqhong/RyzenTuner#10]
设备为 6800H，65W PD 充电，功耗测试为 AIDA 64 单烤 FPU，手动模式正常生效。
重启删除后重新解压，修改 RyzenTuner.exe.config 后再启动。（按 FAQ 后关闭后修改同样，稳定复现）
例如以下不生效情况，平衡模式已修改为 26W，但实际仍为内置初始的 16W。

![屏幕截图 2022-08-29 224606](https://user-images.githubusercontent.com/58877008/187229877-2025b161-4d5e-444f-b4f8-1a8d2d531001.png)
![屏幕截图 2022-08-29 224659](https://user-images.githubusercontent.com/58877008/187229899-c60e6123-eec7-424a-b07d-59e16e6955da.png)

**Comment by zqhong** [comment]
https://github.com/zqhong/RyzenTuner/blob/f4d3d717ff45e3b0411b90f6e99136299077e368/Utils/RyzenAdjUtils.cs#L97-L122

很可能是温度墙的设置影响了性能的发挥，平衡模式下限制 60 度。

**Comment by SimonWe1** [comment]
非常感谢你的回复和解答！实测可用。
简易地解决了 65W PD 下，功率大幅波动导致轻度游戏严重卡顿的问题（估计是采用原装 100W 相同电源策略导致）。
会向遇到同样问题的人推荐，再次感谢！

**Comment by zqhong** [comment]
不客气的，也谢谢你提供的反馈信息。

有个需要注意的点，目前 RyzenTuner 在非性能模式下会关闭睿频。关闭睿频能降低 CPU 温度，但也降低了性能。
