### ISSUE TITLE
建议：添加恢复系统默认功耗与电源调度策略的选项

### ISSUE THREAD

**Issue by ShaddockCyan** [zqhong/RyzenTuner#11]
如题，希望能增加一个一键恢复系统默认功耗与电源调度策略的选项

**Comment by zqhong** [comment]
我的笔记本的 CPU 是 AMD Ryzen™ 7 PRO 6850HS，用 ryzenadj 无法获取到功耗数据，返回 `NaN`。其他机型没有测试过。

这个功能可能只有部分型号 CPU 的笔记本能实现，暂时不考虑添加。
