### ISSUE TITLE
On exit reset changes

### ISSUE THREAD

**Issue by l0lGhostlxl** [zqhong/RyzenTuner#17]
Issue:
When exiting the application I am not told the original tdp of the system nor is it reset.

How to fix:
When exiting reset the values to original state

**Comment by zqhong** [comment]
Please refer to this link:https://github.com/zqhong/RyzenTuner/issues/11

Translation of main content:
My laptop's CPU is AMD Ryzen™ 7 PRO 6850HS, the power consumption data cannot be obtained with ryzenadj, and it returns NaN. Other models have not been tested.

This function may only be implemented by some models of CPU notebooks, and we will not consider adding it for the time being.
