### ISSUE TITLE
RyzenTuner删了，Ryzen Controller也打不开（启动界面一直白的），咋办

### ISSUE THREAD

**Issue by LuckStar2022** [zqhong/RyzenTuner#18]
RyzenTuner删了，Ryzen Controller也打不开（启动界面一直白的），咋办

**Comment by zqhong** [comment]
> Ryzen Controller也打不开（启动界面一直白的）

这种可能是 Ryzen Controller 的问题。

建议重启，RyzenTuner 目前的版本不会开机启动。
