### ISSUE TITLE
托盘图标选中后菜单显示不刷新

### ISSUE THREAD

**Issue by Er1cMa** [zqhong/RyzenTuner#2]
![image](https://user-images.githubusercontent.com/102273670/184107282-c23c63af-87df-4dd3-9a06-7ad57262ff39.png)
例如这样，就会发现CPU数据，GPU数据以及功耗数据均不变动……
![image](https://user-images.githubusercontent.com/102273670/184107529-727678a9-40cb-4040-a9bf-66ca123caf2a.png)
望修复

**Comment by zqhong** [comment]
https://github.com/zqhong/RyzenTuner/commit/2f7257790a7b83efb04beb655be1eb270396cb4b

这里修复了这个问题，下次重新编译发布一个版本
