### ISSUE TITLE
Suggestion: 增加设置选项

### ISSUE THREAD

**Issue by Er1cMa** [zqhong/RyzenTuner#3]
1. 希望能在设置里增加一个开机隐藏式（直接进托盘，不显示主界面）的自启动选项（例如，Ryzen Controller的隐藏式启动加上自己设置一个taskschedule里面的任务）
2. 希望能在设置里增加一个选择是否显示托盘图标的选项（但是我不清楚能否实现，例如IDM那种）

**Comment by zqhong** [comment]
第一点，改为启动后最小化窗口。
第二点，暂时不考虑实现。

相关提交：
https://github.com/zqhong/RyzenTuner/commit/2f76244a4d5dff0b3ef0b037023d51057a805ec9
