### ISSUE TITLE
5800H被锁功耗

### ISSUE THREAD

**Issue by Neraldawn** [zqhong/RyzenTuner#4]
5800H打开软件显示报错，但是CPU功耗会被锁定在55-58W左右（正常满载功耗应该在78-85左右），性能受到影响，无法恢复

**Comment by zqhong** [comment]
你使用的 RyzenTuner 的版本是什么？错误提示什么？你有使用手动模式设置功耗吗？

我怀疑可能是关闭睿频导致的。

**Comment by Alittfre** [comment]
5600h没有报错，但使用软件后即使退出重启

> 你使用的 RyzenTuner 的版本是什么？错误提示什么？你有使用手动模式设置功耗吗？
> 
> 我怀疑可能是关闭睿频导致的。你打开任务管理器，对比下 CPU 的当前速度和基准速度。如果当前速度与基准速度相差不多，很可能就是睿频关闭了。
> 
> ## 查询睿频设置
> ```batchfile
> powercfg.exe -q scheme_current sub_processor perfboostmode
> ```
> 
> ## 开启睿频
> 使用管理员模式打开`cmd.exe`，执行下面的代码：
> 
> ```batchfile
> powercfg.exe /SETACVALUEINDEX scheme_current sub_processor perfboostmode 1
> 
> powercfg.exe /SETDCVALUEINDEX scheme_current sub_processor perfboostmode 1
> 
> powercfg.exe /SETACTIVE SCHEME_CURRENT
> ```
> 
> ## 说明
> ```
> /SETACVALUEINDEX：设置【接通电源】相关联的参数
> /SETDCVALUEINDEX：设置【使用电池】相关联的参数
> /SETACTIVE, /S     使系统上的电源方案处于活动状态
> 
> perfboostmode
>      0：Disabled
>      1：Enabled
>      2：Aggressive（官方翻译：高性能，这个模式下睿频频繁）
>      3：Efficient enabled
>      4：Efficient aggressive
> ```
> 
> 参考：https://docs.microsoft.com/en-us/windows-hardware/customize/power-settings/options-for-perf-state-engine-perfboostmode



> 你使用的 RyzenTuner 的版本是什么？错误提示什么？你有使用手动模式设置功耗吗？
> 
> 我怀疑可能是关闭睿频导致的。你打开任务管理器，对比下 CPU 的当前速度和基准速度。如果当前速度与基准速度相差不多，很可能就是睿频关闭了。
> 
> ## 查询睿频设置
> ```batchfile
> powercfg.exe -q scheme_current sub_processor perfboostmode
> ```
> 
> ## 开启睿频
> 使用管理员模式打开`cmd.exe`，执行下面的代码：
> 
> ```batchfile
> powercfg.exe /SETACVALUEINDEX scheme_current sub_processor perfboostmode 1
> 
> powercfg.exe /SETDCVALUEINDEX scheme_current sub_processor perfboostmode 1
> 
> powercfg.exe /SETACTIVE SCHEME_CURRENT
> ```
> 
> ## 说明
> ```
> /SETACVALUEINDEX：设置【接通电源】相关联的参数
> /SETDCVALUEINDEX：设置【使用电池】相关联的参数
> /SETACTIVE, /S     使系统上的电源方案处于活动状态
> 
> perfboostmode
>      0：Disabled
>      1：Enabled
>      2：Aggressive（官方翻译：高性能，这个模式下睿频频繁）
>      3：Efficient enabled
>      4：Efficient aggressive
> ```
> 
> 参考：https://docs.microsoft.com/en-us/windows-hardware/customize/power-settings/options-for-perf-state-engine-perfboostmode

5600h win11 22h2 使用软件时没有报错，但是退出软件且重启后无法睿频，在控制面板还原默认电源计划后正常。（对EnergyStar提个小建议，可以隐藏掉控制台的黑窗口。）

**Comment by Neraldawn** [comment]
用的版本是1.0.4，最后下回Tuner for Ryzen恢复默认配置解决了问题

**Comment by zqhong** [comment]
> 用的版本是1.0.4，最后下回Tuner for Ryzen恢复默认配置解决了问题

好的，谢谢反馈。
如果是功耗墙的限制，重启也能解决问题的。

**Comment by zqhong** [comment]
> 5600h win11 22h2 使用软件时没有报错，但是退出软件且重启后无法睿频，在控制面板还原默认电源计划后正常。（对EnergyStar提个小建议，可以隐藏掉控制台的黑窗口。）

截止到2022年8月18号，RyzenTuner 的性能模式和自动模式下自动切换的性能模式会开启睿频，其他模式均关闭睿频。
如果希望开启睿频，可以切换到性能模式后关闭软件。

> 对EnergyStar提个小建议，可以隐藏掉控制台的黑窗口
这个黑窗口是怎样的？方便截图吗？我是 Windows 10 的环境，还没有去测试 EnergyStar

**Comment by Alittfre** [comment]
> 

黑窗口：
![c00624f2a2ca300c4ca313967a07e7a5c35acc76](https://user-images.githubusercontent.com/51853302/185268861-9e41d5a2-d180-4382-8eaa-4eb39697844d.jpeg)
（截图网上找的，EnergyStar初版我自己编译后运行也有这个窗口，后续的release不会弹出窗口了，后台静默运行。）

**Comment by zqhong** [comment]
> 黑窗口： ![c00624f2a2ca300c4ca313967a07e7a5c35acc76](https://user-images.githubusercontent.com/51853302/185268861-9e41d5a2-d180-4382-8eaa-4eb39697844d.jpeg) （截图网上找的，EnergyStar初版我自己编译后运行也有这个窗口，后续的release不会弹出窗口了，后台静默运行。）

这个 EnergyStar 是另一个项目，默认是命令行程序，黑窗口是正常的。

RyzenTuner 集成了 EnergyStar，后台静默运行。

相关代码：
https://github.com/zqhong/RyzenTuner/blob/master/UI/MainForm.cs#L100-L115

后续的计划是参考 EnergyStar 的代码，直接调用系统 API，而不是使用 EnergyStar.exe。

**Comment by Neraldawn** [comment]
其实重启并没有解决问题，还是用上述软件恢复了默认配置才解决了

**Comment by zqhong** [comment]
> 其实重启并没有解决问题，还是用上述软件恢复了默认配置才解决了

谢谢反馈。Tuner for Ryzen 的回复默认配置是将功耗墙设置为100W。

参考：
https://github.com/Archeb/RyzenTuner/blob/b039cbce62bab18e4f227e9b2eacf21a6d4fa007/Properties/Settings.settings#L26-L28

**Comment by zqhong** [comment]
> 5800H打开软件显示报错，但是CPU功耗会被锁定在55-58W左右（正常满载功耗应该在78-85左右），性能受到影响，无法恢复

你可以试试看用 v1.1.1 这个版本，尝试对报错进行处理：
https://github.com/zqhong/RyzenTuner/releases/tag/v1.1.1
