### ISSUE TITLE
托盘图标右键勾选样式错误及显示逻辑问题

### ISSUE THREAD

**Issue by duanluan** [zqhong/RyzenTuner#6]
Windows 11 最新版下托盘图标右键的勾选样式有问题：
![image](https://user-images.githubusercontent.com/14957667/185303325-a94f6b34-83de-4b6e-955e-4e179ca9b920.png)

然后此时我点击“自动模式”，就没有任何一项勾选了，但实际上这些选项是单选的。
![image](https://user-images.githubusercontent.com/14957667/185303486-7ddaec45-697b-4ce8-8f8c-97c207b8bfbf.png)

**Comment by zqhong** [comment]
Windows 10 能复现问题，谢谢反馈。

**Comment by zqhong** [comment]
已修复，下个版本发布

**Comment by zqhong** [comment]
你的截图里面还有另一个问题，就是托盘菜单选项的选中效果有点奇怪。这个也处理了。

原来：
![image](https://user-images.githubusercontent.com/8402647/185355554-3bee0691-5993-42d0-998d-5623b45f507f.png)

调整后：
![image](https://user-images.githubusercontent.com/8402647/185355295-d6894aca-81ef-4e09-b88f-a326d5eb4cf7.png)

相关提交：
https://github.com/zqhong/RyzenTuner/commit/aeef5a71ce455d1551ed30b550bbef3716d6987a
