### ISSUE TITLE
托盘图标右键菜单样式问题

### ISSUE THREAD

**Issue by zcf0508** [zqhong/RyzenTuner#7]
版本 v1.1.1

![Snipaste_2022-08-18_21-33-29](https://dubai-1254282834.cos.ap-nanjing.myqcloud.com/Snipaste_2022-08-18_21-33-29.png?imageMogr2/format/webp)

**Comment by zqhong** [comment]
谢谢反馈，已修复。

![image](https://user-images.githubusercontent.com/8402647/185424990-668e1859-de9c-4daa-98b7-1170e8e74360.png)

相关提交：
https://github.com/zqhong/RyzenTuner/commit/aeef5a71ce455d1551ed30b550bbef3716d6987a

下个版本发。
