### ISSUE TITLE
建议新增“开机启动”的设置项

### ISSUE THREAD

**Issue by duanluan** [zqhong/RyzenTuner#8]
建议增加开机自启动的配置项，可以先实现个简单的，比如搞个快捷方式到“启动”目录。

**Comment by duanluan** [comment]
突然觉得这样的右键也不错。
![image](https://user-images.githubusercontent.com/14957667/185528603-0e99eb11-ac89-4a0d-849b-d88c89e97eb1.png)

**Comment by zqhong** [comment]
谢谢反馈。

[原版](https://github.com/Archeb/RyzenTuner)是有这个功能的，通过注册成系统的服务实现。

开机启动设置项等后续功能完善后再考虑。

![image](https://user-images.githubusercontent.com/8402647/185529757-827c1d9f-cae9-4c17-ad71-c607bd9b9141.png)
