### ISSUE TITLE
启动失败，提示init ryzenadj failed

### ISSUE THREAD

**Issue by bsns** [zqhong/RyzenTuner#9]
![1661393780616](https://user-images.githubusercontent.com/8208260/186558869-564d9373-4c22-4319-afd1-4823949e0b30.jpg)
系统信息：win11 22H2  
处理器：AMD 6800H

**Comment by zqhong** [comment]
下载 https://github.com/FlyGoat/RyzenAdj/releases/download/v0.11.1/ryzenadj-win64.zip

使用管理员身份打开 `cmd.exe`，执行 `ryzenadj.exe`

提供执行结果，如果确实有 bug，请提交 https://github.com/FlyGoat/RyzenAdj/issues

**Comment by bsns** [comment]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/8208260/186562209-5e80f4ef-239a-43af-bf02-e6945c70d667.png">
ryzenadj正常，可以使用

**Comment by zqhong** [comment]
那你试试看 `./ryzenadj --stapm-limit=45000 --fast-limit=45000 --slow-limit=45000 --tctl-temp=90`，看看提示什么。

你的 RyzenTuner 是哪个版本的？

**Comment by zqhong** [comment]
@bsns 
你好，目前问题是否解决了？具体什么原因？

**Comment by bsns** [comment]
测试正常了；
看ryzenadj的issue，有可能是 安全启动 的原因。
我很久之前就关闭过；但是我查阅记录，发现win11的系统更新可以更新bios版本，导致设置被刷新，重新关闭后就正常了。

**Comment by zqhong** [comment]
谢谢反馈！
